### ISSUE TITLE
issue in the code #line19 (install.py)

### ISSUE THREAD

**Issue by Harsh-m342** [hacksec-in/hacksec-cli#2]
![issue](https://user-images.githubusercontent.com/57844670/132939191-82da793b-01dd-4715-8c0d-65238e93f082.PNG)

the issue lies in line 19 where the variable **"install_dir"** is a  _str_ type object and method **"isdir()"** is not an attribute of string type.

Correction:
![issue_resolved](https://user-images.githubusercontent.com/57844670/132939277-b1928235-88db-467c-ac63-86bd3656e60f.PNG)

the code can be resolved using the **os.path.isdir()** in place of **install_dir.isdir()**

**Comment by ScRiPt1337** [comment]
Thanks for letting me know i just fix it
